name: Java CI

on:
  push:
    branches:
      - master
    paths:
      - '**.java'
      - '**.gradle'
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    name: Java ${{ matrix.java }} setup

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1

        with:
          java-version: ${{ matrix.java }}

      - name: Code Style
        run: ./gradlew spotlessCheck

      - name: Build
        run: ./gradlew shadowJar

      - name: Benchmark [goodforgod-simple-logger]
        run: java -jar goodforgod-simple-logger/build/libs/*-all.jar 2>/dev/null

      - name: Benchmark [slf4j-simple-logger]
        run: java -jar slf4j-simple-logger/build/libs/*-all.jar 2>/dev/null

      - name: Benchmark [logback-logger]
        run: java -jar logback-logger/build/libs/*-all.jar 2>/dev/null

      - name: Benchmark [log4j-logger]
        run: java -jar log4j-logger/build/libs/*-all.jar 2>/dev/null

      - name: Benchmark [system-logger]
        run: java -jar system-logger/build/libs/*-all.jar 2>/dev/null
